# Cloud Build 配置檔
# 用於自動化部署到 Cloud Run

steps:
  # 建置 Docker 映像
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hsus-order-status:$SHORT_SHA', '.']
  
  # 推送映像到 Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/hsus-order-status:$SHORT_SHA']
  
  # 部署到 Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'hsus-order-status'
      - '--image'
      - 'gcr.io/$PROJECT_ID/hsus-order-status:$SHORT_SHA'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/hsus-order-status:$SHORT_SHA'

options:
  machineType: 'N1_HIGHCPU_8'

